#!/bin/bash
# THE LANDING SWEEP — epic-16 wave-01 (the gate), wave-03 slice T4c (the sweep).
#
# Stop. On every orchestrator turn end, during an active wave: read this session's roster,
# take a landing verdict for every contract that has LANDED since the last sweep, and refuse
# the stop once if any of them named artifacts that are not on disk. Outside an active wave,
# or on any ambiguity along the way, the stop passes through untouched.
#
# WHY A SWEEP, AND WHY ON THIS EVENT. Until wave-03 this ran on the subagent's own stop and
# judged the one agent that stopped. That event cannot reach it any more, and not by
# accident: skill-frontmatter hooks live in the harness's `appState.sessionHooks`, keyed by
# SESSION id, and the subagent-stop path looks them up under `agentId ?? session.id` — the
# subagent's id, which has no entry. Every event dispatched in a subagent context is
# therefore structurally invisible to a skill-registered hook, so a wall registered there is
# installed, syntactically fine, green in its own suite, and never runs
# (record/session-20260814-wave-detector-terminal-state/t4b-probe-report.md §3, read out of
# the shipped binary and confirmed by an eleven-session dual-channel A/B).
#
# `Stop` is delivered to that channel, fires once per orchestrator turn, keeps firing on
# turns the skill was not re-invoked on — and, the fact that makes the latency a non-issue,
# is GENERATED BY a background agent's landing: the completion wakes a fresh turn, which
# closes 2.5–3.7 s later and delivers a Stop nobody asked for (§2.3, §4, two independent
# replications). So a sweep here runs both when the orchestrator pauses and shortly after
# each landing, which is exactly the two moments a landing contract cares about.
#
# HOW A LANDING IS RECOGNISED. The payload carries `background_tasks[]`, one row per
# subagent that is STILL RUNNING, keyed by the same `id` the roster's `agent_id=` holds —
# `tool_response.agentId` at dispatch, `agent_id` on SubagentStart, `background_tasks[].id`
# here, one string across all three (§2.2, §4, measured on one dispatch). A roster row whose
# id is ABSENT from that list has landed; a row still on it is skipped in silence. Nothing
# on this path reads `agent_type`, which carries the subagent TYPE and never the dispatch
# name — the join defect t4-probes-report.md §5.1 found open and this slice closes.
#
# ONCE PER ROW, EVER. Stop fires every turn and a landed row stays landed, so a sweep that
# re-verdicted would refuse every turn end for the rest of the session over one agent's
# failure — the false-alarm shape this machinery exists to end. Each verdicted row is
# journalled as a `landing-swept/v1|` line in the roster file it belongs to. That is the one
# thing this script writes, and it rides IN the roster because the promise it keeps must not
# outlive the rows it is about. Inertness to the rest of the fleet is NOT a blanket property
# of every roster reader — it holds per reader, for one of two separate reasons, and both
# must be true or the marker leaks into a reader's answer (t6-review.md F-1, reproduced live:
# `hooks/session-poker.sh` read the roster with no schema filter and the marker silenced its
# overdue NOTIFY for the swept row). `hooks/execution-recorder.sh`, `hooks/session-sweeper.sh`,
# `hooks/stop-guard.sh`, `hooks/stop-check.sh` and `hooks/stop-orders.sh` filter on the
# `roster-state/v1|` prefix before reading a row, so the marker's `landing-swept/v1|` prefix
# never matches. `hooks/dispatch-preflight.sh` does NOT filter on that prefix and is immune
# only by accident: its `owning_row_for` skips any row with no `deliverable=`, a field the
# marker never carries. That second immunity is undeclared to its own reader and untested —
# one added field to the marker's schema would turn it into a second instance of this bug.
#
# IT OWNS NO PREDICATE. The question "did this contract land" is answered by
# `hooks/session-sweeper.sh verdict <name>`, and this script parses that verb's machine line
# for `state=`, `acked=` and `detail=`. It never stats a deliverable and never forms an
# opinion about staleness, waivers or liveness-by-progress. It reads exactly two fields of
# the roster for itself — `agent_id`, which is the join key above, and `name`, which is what
# the verb must be asked about — plus `deliverable` as a pure PREFILTER: a row declaring
# nothing is MET vacuously by the verb's own rule, so skipping it cannot change an answer,
# only the cost of getting one.
#
# THE SECOND ARM: TEAMMATES LAND AT SubagentStop (session-20260815, T2; design D2).
# Everything above is true of an async subagent and false of a named teammate. A teammate
# carries THREE id namespaces that do not join — the addressing form at dispatch
# (`mate@session-7b7a693c`), the transcript form on SubagentStart/Stop
# (`amate-fdaa80c4b3cb703f`), and an opaque nine-character token in `background_tasks[]` that
# appears in no dispatch-time payload at all — and its row NEVER LEAVES that array: measured
# `status:"running"` on the last Stop of the session, 2 m 41 s after the teammate had
# delivered its own SubagentStop (t1-probe-report.md §2.1–§2.3, CLI 2.1.233). So the sweep
# predicate is not merely unjoinable for teammates, it is wrong in both directions: today
# every teammate row is skipped for want of an id, and the moment a writer fills one, every
# teammate reads as LANDED 2.8 s after dispatch, while it is still working.
#
# `SubagentStop` is the transition itself rather than a reconstruction of it, and it carries
# the id, the name and the moment in one payload. This arm therefore takes the SAME verdict
# from the SAME verb, writes the SAME marker through the SAME append, and speaks the SAME
# refusal — what differs is only which row is judged and when. It reads no live set (the
# stopping teammate is still in it), joins by `agent_id` first and by `agent_type` — which
# carries the dispatch NAME for a teammate — second, and both joins are scoped to rows
# carrying a non-empty `teammate_id=`.
#
# THAT SCOPE CUTS BOTH WAYS, and the sweep half of it is in the fold below: teammate rows are
# skipped there, with the one exception the next paragraph names. An async subagent stopping on this event is passed over in silence, because
# the sweep is the arm that owns it and the marker written here is exactly what would tell
# the sweep the row is already answered for — verdicting an async row here would not
# duplicate the sweep, it would silently replace the refusal the orchestrator sees with one
# delivered somewhere else.
#
# THE SUPERSESSION RECHECK (session-20260815-landing-cleanup, T3; ruling: supersede). The one
# thing the sweep does with a teammate row, and it is not a verdict. A refused teammate is
# told inside its own sidechain at the one moment it can still act, and it acts: measured
# live, the teammate read the feedback, wrote the promised artifact, and the roster still read
# `state=UNMET` when the session ended (record/session-20260815-landing-supervision/
# live-verify.md §B2). The refusal was correct and its record was a false statement about the
# world. So on any later Stop, a teammate row whose LATEST marker says UNMET and whose
# deliverable the verb now finds gets a SECOND marker appended, saying MET. Both persist, in
# order: the stream is history plus current state, and nothing is ever rewritten. It never
# refuses, it never writes a FIRST verdict for a teammate (an unmarked row stays the
# SubagentStop arm's, delivered or not), it costs nothing once the answer is MET, and it needs
# no clock of its own — Stop already fires on every turn end and shortly after every landing.
#
# WHERE THE REFUSAL GOES, stated because it differs from the sweep and the difference is not
# ours to change: a blocking Stop-hook exit on the main thread reaches the orchestrator,
# while on SubagentStop the harness delivers the feedback TO THE SUBAGENT and lets it
# continue so it can act on it (read out of the shipped CLI 2.1.233 binary:
# "additionalContext is non-error feedback delivered to the subagent; the subagent continues
# so it can act on it", beside the block-cap guidance "For Stop/SubagentStop hooks, check
# stop_hook_active in the input and return success while it is true"). So the agent that
# broke its contract is the one told about it, at the one moment it can still fix it, and the
# orchestrator-facing record is the roster marker plus the poker overdue NOTIFY that reads
# the same rows. `stop_hook_active` is honoured here for the reason the binary gives.
#
# FAIL DIRECTIONS (pinned by tests/landing-gate.test.sh):
#   - not a Stop or SubagentStop payload                 -> pass, silent (relevance hoist)
#   - SubagentStop with no agent_id, or one carrying
#     field separators                                   -> pass, silent
#   - SubagentStop matching no teammate row (a phantom
#     harness agent, or an async subagent the sweep
#     owns)                                              -> pass, silent
#   - no `background_tasks` key: nothing to tell landed
#     from live                                          -> pass, silent (ambiguity)
#   - stop_hook_active true                              -> pass, silent (blocks ONCE)
#   - cwd/repo unresolvable, or no session_id, or a
#     session_id that is not shaped like one             -> pass, silent (ambiguity)
#   - no roster for this session, or a symlinked one     -> pass, silent
#   - no active wave                                     -> pass, silent
#   - the sweeper is absent                              -> pass, silent
#   - a row with an EMPTY agent_id: it cannot be placed
#     on either side of the landed/live line             -> skip, unmarked (ambiguity)
#   - the verdict exits anything but 0 or 1, or prints
#     no line at all                                     -> skip, UNMARKED (no answer, so
#                                                          the row is still owed one)
#   - the verdict says anything but UNMET, or says UNMET
#     over an acked row                                  -> mark swept, pass
#   - the verdict says UNMET on a landed row             -> REFUSE, quoting its detail
#   - a swept teammate row, latest marker UNMET, and the
#     verdict now says MET                               -> append a superseding marker, pass
#   - the same row, verdict still anything but MET       -> nothing appended, pass, silent
#   - a teammate row with NO marker at all               -> skip, unmarked (never a first
#                                                          verdict from this event)
#
# Exit code 2 = block the stop in Claude Code hooks; stderr goes back to the orchestrator,
# which is why the refusal must name the row and its artifacts rather than the rule.
# [WALL: tests/landing-gate.test.sh]
#
# Registered on both channels: hooks/hooks.json (agent contexts, behind agent-context-guard.sh) and skills/canonical-sdlc/SKILL.md frontmatter (main thread).

set -uo pipefail

SWEPT_SCHEMA="landing-swept/v1"
# Reader copy of hooks/dispatch-preflight.sh's roster constant, on the same precedent
# hooks/session-sweeper.sh states for its copy: a prefix drift here is a mislabeled scan.
ROSTER_VERSION="v1"

INPUT=$(cat)
_jq() { printf '%s' "$INPUT" | jq -r "$1 // empty" 2>/dev/null; }

# ---------- relevance first: the cheapest checks, before any git resolution ----------

# TWO EVENTS, TWO ARMS, ONE ROSTER SPLIT BETWEEN THEM. `Stop` is the sweep (below);
# `SubagentStop` is the teammate landing verdict, and it arrives on the settings channel
# behind hooks/agent-context-guard.sh because no subagent-context event reaches the skill
# frontmatter at all. An absent field is not treated as a mismatch, so a hand-run payload
# still sweeps.
EVENT=$(_jq '.hook_event_name')
case "$EVENT" in
  ""|Stop)      MODE=sweep ;;
  SubagentStop) MODE=landing ;;
  *)            exit 0 ;;
esac

# Read on BOTH paths, so neither is a variable bound on only some of them (`set -u`), and
# read here rather than at the join so the shape checks sit beside every other one.
STOP_AGENT_ID=""
STOP_AGENT_NAME=""
LIVE_IDS=""

if [ "$MODE" = "sweep" ]; then
  # THE LIVE SET, and the whole of the landed/live discrimination. Its ABSENCE is not an empty
  # set: an empty array means every dispatch has finished (the payload says so on every turn
  # where nothing is running), while a missing key means this is not a payload that can tell
  # us, and judging on it would hold running agents to contracts they are still working on.
  [ "$(printf '%s' "$INPUT" | jq -r 'if has("background_tasks") then "yes" else empty end' 2>/dev/null)" = "yes" ] || exit 0
  LIVE_IDS="|$(printf '%s' "$INPUT" \
    | jq -r '[.background_tasks[]?.id // empty] | join("|")' 2>/dev/null | tr -d '\n')|"
else
  # THE LANDING ARM READS NO LIVE SET, and that is the point of it rather than an omission.
  # This payload carries `background_tasks[]` too, and the stopping teammate is STILL IN IT —
  # measured `status:"running"` on the last Stop of the session, 2 m 41 s after its own
  # SubagentStop, because an in-process teammate stays addressable until the session ends
  # (t1-probe-report.md §2.3). Landing-by-disappearance is a subagent-only signal; here the
  # EVENT is the landing, delivered with the id, the name and the moment in one payload.
  STOP_AGENT_ID=$(_jq '.agent_id')
  [ -n "$STOP_AGENT_ID" ] || exit 0
  # SHAPE-CHECKED BEFORE IT BECOMES A FIELD, on the same reasoning the session key gets: this
  # value is written into a `landing-swept/v1|…|agent_id=` marker line, and a `|` or a newline
  # in it would forge a field or a whole row on the roster. The transcript form is
  # `a<name>-<16 hex>` and names are alphanumeric, so this silences nothing real.
  case "$STOP_AGENT_ID" in *[!A-Za-z0-9_.@-]*) exit 0 ;; esac
  # The NAME, for the fallback join, and only if it is shaped like one. `agent_type` carries
  # the dispatch name for a teammate and the subagent type for an async dispatch (t1 §2.1);
  # the harness's own phantom agents send it empty. An unusable value drops the fallback
  # rather than the whole arm — the id join above may still place the row.
  STOP_AGENT_NAME=$(_jq '.agent_type')
  case "$STOP_AGENT_NAME" in *[!A-Za-z0-9_-]*) STOP_AGENT_NAME="" ;; esac
fi

# BLOCKS ONCE, and this is the whole mechanism. Claude Code re-enters the stop with
# stop_hook_active true after a hook blocked it; refusing again would wedge the turn in a
# loop it has no way out of. One refusal names the contracts; the second stop is the
# orchestrator's to decide about. (jq's `//` folds `false` to empty, so a literal "true" is
# the only value that can match here — which is the comparison we want anyway.) Nothing is
# verdicted on a re-entry either: the rows are still owed their one answer.
[ "$(_jq '.stop_hook_active')" = "true" ] && exit 0

# ---------- ambiguity: cannot locate the repo or the session -> pass, silent ----------
CWD=$(_jq '.cwd')
[ -n "$CWD" ] || exit 0
REPO=$(git -C "$CWD" rev-parse --show-toplevel 2>/dev/null) || exit 0
[ -n "$REPO" ] || exit 0

# The PAYLOAD's session key, never the ambient environment's: this script runs inside a hook
# process whose env is not a documented carrier of the session id, and the payload is the
# authority on whose roster this stop belongs to. It is passed to the sweeper below for the
# same reason.
SID=$(_jq '.session_id')
[ -n "$SID" ] || exit 0
# SHAPE-CHECKED BEFORE IT BECOMES A PATH, exactly as hooks/dispatch-preflight.sh checks it.
# This value is interpolated into `roster-${SID}.state` below — a file this script now
# APPENDS to — and exported to the sweeper, which builds its own ledger and findings paths
# from it; the symlink guards on those paths check the state directory and the exact
# filenames, so a key carrying separators does not trip a guard, it leaves the directory the
# guards protect. Session ids are harness-minted UUIDs today and nothing reaches this, but
# every other payload value on this path is sanitized and this one was not (Step-6 S-4).
case "$SID" in *[!A-Za-z0-9_-]*) exit 0 ;; esac

ROSTER_FILE="$REPO/.bionic/tmp/roster-${SID}.state"
# Existence first, so a session that has dispatched nothing costs one stat. The symlink
# guard is the write half of TDD §8: a repo controls its own .bionic/, and a link at any
# level redirects this script's marker append outside the repo.
[ -e "$ROSTER_FILE" ] || exit 0
[ -L "$REPO/.bionic" ] && exit 0
[ -L "$REPO/.bionic/tmp" ] && exit 0
[ -L "$ROSTER_FILE" ] && exit 0

# ---------- active-wave detection ----------
# DELIBERATELY DUPLICATED, byte for byte where the logic overlaps, from
# hooks/dispatch-preflight.sh's copy (stop-guard, execution-recorder and the evidence gate
# hold the others). A shared library is rejected by design (TDD §9): a sourced file the
# installer misses is a silently inert wall. The copies are held together by
# tests/cross-gate-agreement.test.sh.
resolve_docs_root() {
  local proj="$1" config="$1/.bionic/config.yaml" override
  if [ -f "$config" ]; then
    override=$(grep -E '^[[:space:]]*docs-root[[:space:]]*:' "$config" 2>/dev/null \
      | head -1 \
      | sed -E 's/^[[:space:]]*docs-root[[:space:]]*:[[:space:]]*//' \
      | sed -E "s/^['\"]//;s/['\"]\$//" \
      | sed -E 's/[[:space:]]+$//')
    if [ -n "$override" ]; then
      case "$override" in
        /*) echo "$override" ;;
        *)  echo "$proj/$override" ;;
      esac
      return
    fi
  fi
  echo "$proj/.bionic/docs"
}

# A CANDIDATE IS A PLAN ONLY IF IT CARRIES AN UNFENCED `## SDLC State` HEADING.
# Without this filter a stray marker-less *.md that happens to be newest under
# plans/ — a continuation note, a Step-9 artifact, a probe scrap — WINS the
# newest race, `current:` parses empty, and every wall reading this block passes
# silently while a wave is live. That is measured, not hypothetical: it disarmed
# the dispatch wall repo-wide for ~15 minutes on 2026-08-15, and again in the
# probe that investigated it, neither time on purpose
# (record/session-20260815-landing-supervision/t8-forensic-read.md).
# Fence-aware, because the read it feeds is: a schema example is documentation,
# not a run. Line endings TRANSLATED, never deleted, for the reason spelled out
# at the `current:` read. A file that cannot be read is not a candidate — falling
# back to an older real plan keeps the walls armed, the safe direction. Skipping
# EVERY candidate lands where finding none lands: no wave, pass, silent.
has_sdlc_state() {
  awk '{ sub(/\r$/, ""); gsub(/\r/, "\n"); print }' "$1" 2>/dev/null | awk '
    /^[[:space:]]*```/ { fence = !fence; next }
    fence { next }
    /^## SDLC State/ { found = 1 }
    END { exit !found }'
}

DOCS_ROOT=$(resolve_docs_root "$REPO")
PLAN=""
for d in "$DOCS_ROOT/plans" "$DOCS_ROOT/incidents"; do
  [ -d "$d" ] || continue
  while IFS= read -r -d '' f; do
    if [ -z "$PLAN" ] || [ "$f" -nt "$PLAN" ]; then
      has_sdlc_state "$f" || continue
      PLAN="$f"
    fi
  done < <(find "$d" -maxdepth 2 -type f -name '*.md' -print0 2>/dev/null)
done
[ -n "$PLAN" ] && [ -f "$PLAN" ] || exit 0

# The run-state marker, read exactly as the evidence gate, stop-guard and the dispatch gate
# read it: the fence-aware ## SDLC State section, then its `current:` value. Line endings
# TRANSLATED, never deleted — see .claude/rules/hook-authoring.md (a CR-only file deleted by
# `tr -d '\r'` collapses to one line and every line-anchored match misses, going silently
# inert with a wave live).
CURRENT=$(awk '{ sub(/\r$/, ""); gsub(/\r/, "\n"); print }' "$PLAN" 2>/dev/null | awk '
  /^[[:space:]]*```/ { fence = !fence; next }
  fence { next }
  /^## SDLC State/ { flag=1; next }
  /^## / { flag=0 }
  flag' \
  | grep -E '^[[:space:]]*current[[:space:]]*:' \
  | head -1 \
  | sed -E 's/^[[:space:]]*current[[:space:]]*:[[:space:]]*//' \
  | tr -d '[:space:]')
echo "$CURRENT" | grep -qE '^([0-9]+[ab]?|T[0-9]+)$' || exit 0

# ---------- a wave is active: sweep ----------

# The sweeper is this script's SIBLING — the payload ships every hooks/*.sh in one
# directory, so the same resolution holds in the repo and under the mounted plugin's
# hooks/ that hooks/hooks.json roots at ${CLAUDE_PLUGIN_ROOT}. No PATH
# lookup (a hook's PATH is not ours to trust) and no environment override (a seam on the
# path under test would leave the production path unverified).
SWEEPER="$(cd "$(dirname "$0")" 2>/dev/null && pwd)/session-sweeper.sh"
[ -f "$SWEEPER" ] || exit 0

# ONE PASS OVER THE ROSTER, and it is the only cost this script pays on a turn where nothing
# landed. The fold rule is hooks/session-sweeper.sh's own (`latest_rows`), because the verb
# is what will be asked and a reader that folded differently would ask about a row the verb
# never answers for: rows of THIS session only, keyed by name, FIRST field of a key wins
# within a row, latest row wins across them, an empty name folds to `(unnamed)`.
#
# `agent_id` is taken from the latest row that CARRIES one rather than from the latest row
# outright. The field starts empty on the `intended` row the dispatch wall writes and is
# filled by hooks/execution-recorder.sh at confirmation; it never goes back to empty, so
# this is monotone rather than a preference, and it keeps a row joinable if a future writer
# ever appends without copying it forward.
#
# The output is TAB-delimited `<agent_id> <name> <kind>`, one line per unswept, joinable,
# contract-bearing row. A tab cannot appear inside a field — every writer on this roster runs
# its values through a sanitizer that turns one into a space — and the name is folded the
# same way the verb folds it. `kind` is `verdict` for a row being answered for the first (and
# only) time, and `recheck` for the supersession arm below, which is the one caller that may
# write a SECOND marker for a row and the one that never refuses.
CANDIDATES=$(awk -v pfx="roster-state/${ROSTER_VERSION}|" -v spfx="${SWEPT_SCHEMA}|" -v sid="$SID" \
                 -v mode="$MODE" -v pid="$STOP_AGENT_ID" -v atype="$STOP_AGENT_NAME" '
  index($0, spfx) == 1 {
    nf = split($0, f, "|"); a = ""; mn = ""; ms = ""
    for (i = 1; i <= nf; i++) {
      if (a  == "" && substr(f[i], 1,  9) == "agent_id=") a  = substr(f[i], 10)
      if (mn == "" && substr(f[i], 1,  5) == "name=")     mn = substr(f[i], 6)
      if (ms == "" && substr(f[i], 1,  6) == "state=")    ms = substr(f[i], 7)
    }
    if (a != "") swept[a] = 1
    # THE LATEST ANSWER, PER ROW, and latest means LAST IN THE FILE: this is an append-only
    # journal, so file order is chronological and an unconditional assignment leaves the most
    # recent marker standing. The recheck arm below reads exactly these two facts — what the
    # last answer said, and which id it was keyed by — and asks for nothing the marker does
    # not already carry.
    if (mn != "") { mstate[mn] = ms; if (a != "") magent[mn] = a }
    next
  }
  index($0, pfx) != 1 { next }
  {
    name = ""; rsession = ""; aid = ""; deliv = ""; tid = ""
    nf = split($0, f, "|")
    for (i = 1; i <= nf; i++) {
      if (name == ""     && substr(f[i], 1, 5)  == "name=")        name     = substr(f[i], 6)
      if (rsession == "" && substr(f[i], 1, 8)  == "session=")     rsession = substr(f[i], 9)
      if (aid == ""      && substr(f[i], 1, 9)  == "agent_id=")    aid      = substr(f[i], 10)
      if (deliv == ""    && substr(f[i], 1, 12) == "deliverable=") deliv    = substr(f[i], 13)
      if (tid == ""      && substr(f[i], 1, 12) == "teammate_id=") tid      = substr(f[i], 13)
    }
    # The roster file is already per-session; this only fires on a hand-edited or copied
    # file, and it costs one comparison to keep the sweep honest about whose promises it is
    # answering for.
    if (rsession != "" && rsession != sid) next
    if (name == "") name = "(unnamed)"
    gsub(/\t/, " ", name)
    if (!(name in seen)) { seen[name] = 1; order[++n] = name }
    if (aid != "") agent[name] = aid
    # `teammate_id` is monotone the way `agent_id` is — the launch wall never writes it and
    # the completion arm fills it once — so the latest row that CARRIES one wins, and a row
    # appended without copying it forward cannot un-teammate a contract.
    if (tid != "") tm[name] = tid
    dl[name] = deliv
  }
  END {
    # ---------- the landing arm: ONE row, the one that just stopped ----------
    if (mode == "landing") {
      nm = ""
      # BY ID FIRST. The transcript form is filled onto the row by the recorder at
      # SubagentStart, and it is the same string this payload carries — the strongest key
      # available, and the one that survives two dispatches sharing a name.
      for (i = 1; i <= n; i++) {
        k = order[i]
        if (tm[k] == "") continue
        if ((k in agent) && agent[k] != "" && agent[k] == pid) nm = k
      }
      # BY NAME SECOND, and only over teammate rows. For a teammate `agent_type` carries the
      # dispatch name; for an async dispatch it carries the subagent type, which names no row
      # and is the join wave-03 removed for cause. The scope reads the statement the row
      # writer made about dispatch mode, never a guess at the shape of an id.
      if (nm == "" && atype != "" && (atype in seen) && tm[atype] != "") nm = atype
      # A stop we cannot place is not ours to answer for: the harness sends its own internal
      # agents through this event, and their ids are on no row of ours.
      if (nm == "") exit
      if (dl[nm] == "") exit                # declares nothing; MET vacuously either way
      a = ((nm in agent) && agent[nm] != "") ? agent[nm] : pid
      if (a == "") exit
      # Both keys, because the marker may have been written under either: the row id when the
      # identification arm ran, the payload id when it did not.
      if ((a in swept) || (pid in swept)) exit
      printf "%s\t%s\t%s\n", a, nm, "verdict"
      exit
    }

    # ---------- the sweep: every row the payload says has landed ----------
    for (i = 1; i <= n; i++) {
      nm = order[i]
      # TEAMMATES BELONG TO THE OTHER ARM, and this skip is load-bearing rather than tidy.
      # A teammate is keyed in `background_tasks[]` under a namespace its `agent_id` is not
      # in, and it NEVER LEAVES that array anyway (t1 §2.3) — so the moment the recorder
      # fills the row id, the landed/live predicate here reads every teammate as landed on
      # the first Stop after dispatch, 2.8 s in, and refuses a contract the agent is still
      # working on. The sweep judges what it can place; the SubagentStop arm judges the rest.
      #
      # ONE EXCEPTION, AND IT IS NOT A VERDICT (session-20260815-landing-cleanup T3, AC-5).
      # A teammate refused at SubagentStop is told so INSIDE its own sidechain, at the one
      # moment it can still act — and it does: measured live, the refused teammate read the
      # feedback and wrote the promised artifact, while the roster still said UNMET when the
      # session ended (live-verify.md B2). The refusal was right and its record was a lie
      # about the world. So a teammate row whose LATEST marker says UNMET, and whose
      # contracted deliverable the verb now finds, gets a SUPERSEDING marker appended: the
      # stream carries history plus current state, nothing is rewritten, and the block-once
      # promise is untouched because a supersession never speaks. The Stop cadence is the
      # clock; no timer is added for it.
      #
      # NEVER A FIRST VERDICT. A teammate row with no marker at all is left exactly where the
      # skip above leaves it, delivered or not — the sweep cannot tell a working teammate
      # from a finished one, and answering here is the 2.8-second false refusal this whole
      # partition exists to prevent. The recheck can only ever change an answer that the
      # SubagentStop arm already gave.
      if (tm[nm] != "") {
        if (!(nm in mstate)) continue       # unanswered: not this arm to answer
        if (mstate[nm] != "UNMET") continue # the current answer is no failure; nothing to supersede
        if (dl[nm] == "") continue          # declares nothing; MET vacuously either way
        ra = ""
        # The id off the MARKER first, and the row only as a fallback: in teammate mode a row
        # carries no `agent_id=` at all (the addressing form lives in `teammate_id=`), and the
        # marker was keyed by the transcript form off the stopping payload. Superseding under
        # a different key would leave two markers no reader could tell were about one answer.
        if ((nm in magent) && magent[nm] != "") ra = magent[nm]
        # UNREACHABLE while this file is the only writer of landing-swept marker lines
        # (Step-6 review flag 3-A; grep -rn SWEPT_SCHEMA hooks/*.sh confirms one writer,
        # below in this file) and its write path refuses to append unless agent_id is
        # non-empty, so magent[nm] is always populated whenever mstate[nm] exists.
        # Kept as belt-on-belt against a future second writer, not a live path.
        else if ((nm in agent) && agent[nm] != "") ra = agent[nm]
        if (ra == "") continue
        printf "%s\t%s\t%s\n", ra, nm, "recheck"
        continue
      }
      if (!(nm in agent)) continue          # never confirmed: cannot be placed
      if (dl[nm] == "") continue            # declares nothing; MET vacuously either way
      if (agent[nm] in swept) continue      # already answered for, once and for all
      printf "%s\t%s\t%s\n", agent[nm], nm, "verdict"
    }
  }
' "$ROSTER_FILE" 2>/dev/null)

[ -n "$CANDIDATES" ] || exit 0

LINE=""
_field() {  # <key> — by key, never by position, as every reader of these lines does
  printf '%s' "$LINE" | tr '|' '\n' | grep "^$1=" | head -1 | cut -d= -f2-
}

REFUSALS=""
NOW=$(date -u +%Y-%m-%dT%H:%M:%SZ)

while IFS=$'\t' read -r AID NAME KIND; do
  [ -n "$AID" ] && [ -n "$NAME" ] || continue
  # STILL IN FLIGHT — the payload says so, and an agent that is visibly still working has
  # not failed to land. No verdict, and no marker: its one answer is still owed.
  case "$LIVE_IDS" in *"|$AID|"*) continue ;; esac

  # Run from the repo, because the sweeper resolves its own state directory from the working
  # directory, and with the payload's session key. `|| exit 9` keeps a failed `cd` out of the
  # exit-1 band: exit 1 is the verb's "at least one UNMET row", and nothing else may be
  # allowed to spell it.
  VERDICT=$( cd "$REPO" 2>/dev/null || exit 9
             CLAUDE_CODE_SESSION_ID="$SID" bash "$SWEEPER" verdict "$NAME" 2>/dev/null )
  VERDICT_RC=$?

  # AN ANSWER WE DID NOT GET IS NOT AN ANSWER. Exit 2 is a refusal (the verb was redirected
  # away from the roster and says so), 3 is no session key, anything else is an error — and
  # none of them may mark a row closed, because the row has not been judged.
  case "$VERDICT_RC" in 0|1) : ;; *) continue ;; esac

  # THE LINE THE SCOPED VERB RETURNED, and no second lookup by name. `verdict <name>`
  # answers for that name alone and folds the roster to one row per name, so its output
  # carries at most one machine line and taking the first IS taking this contract's.
  LINE=$(printf '%s\n' "$VERDICT" | grep -F 'landing-verdict/v1|' | head -1)
  [ -n "$LINE" ] || continue

  STATE=$(_field state)

  # A RECHECK SPENDS A MARKER ONLY ON A CHANGED ANSWER. The row already has one saying UNMET;
  # a second saying the same thing records nothing and would be appended on every turn end
  # for the rest of the session — the marker-spam shape. Only MET supersedes: STILL-LIVE,
  # WAIVED and AMBIGUOUS are not the recovery this arm exists to record, and UNMET is the
  # answer already standing.
  if [ "$KIND" = "recheck" ] && [ "$STATE" != "MET" ]; then
    continue
  fi

  # APPENDED HERE, PER ROW, THE MOMENT ITS VERDICT IS DECIDED — not accumulated across the
  # whole loop and written once at the end (t6-review.md F-2, measured: a sweep killed 5s
  # into a 200-candidate run, ~60 already verdicted, banked ZERO marks under the old single
  # trailing append). This is the same lock-free discipline the trailing append relied on —
  # one line, well under a pipe buffer, O_APPEND — just paid once per row instead of once
  # per sweep, so a sweep killed mid-loop still banks every verdict already decided.
  printf '%s|at=%s|session=%s|name=%s|agent_id=%s|state=%s\n' \
    "$SWEPT_SCHEMA" "$NOW" "$SID" "$NAME" "$AID" "$STATE" >> "$ROSTER_FILE" 2>/dev/null

  # AND A SUPERSESSION NEVER SPEAKS. Its marker is MET by construction, so nothing below
  # would fire anyway — but the reason it must not is stronger than the arithmetic: the row
  # has already been refused once, the agent has already acted on that refusal, and the whole
  # promise of this gate is that it blocks once. Recording the recovery is the entire job.
  [ "$KIND" = "recheck" ] && continue

  [ "$VERDICT_RC" -eq 1 ] || continue
  [ "$STATE" = "UNMET" ] || continue

  # AN ACKED ROW IS CLOSED FOR EVERY READER (epic-16 wave-02 slice S3, R2). The orchestrator
  # verified this agent's completion and made that durable; reporting it again over artifacts
  # a human has already accounted for is the false alarm this wave exists to end. Read off
  # the verdict line, which is where the one reader of that ledger publishes it (S9).
  [ "$(_field acked)" = "yes" ] && continue

  # The refusal is the verb's own detail, unedited, prefixed by the row it is about. It names
  # every failing conjunct — `missing=`, `empty=`, `stale=` with both stamps — because a
  # reader told only "unmet" has nothing to act on. The ROW NAME is what the sweep adds and
  # the per-agent gate did not need: a sweep answers about contracts rather than about
  # whoever is stopping, so without it the reader cannot tell which dispatch to chase.
  REFUSALS="${REFUSALS}LANDING CONTRACT UNMET — ${NAME}: $(_field detail). Land the contract (write the named artifacts), or stop again to pass — this gate blocks once.
"
done <<EOF
$CANDIDATES
EOF

[ -n "$REFUSALS" ] || exit 0
printf '%s' "$REFUSALS" >&2
exit 2
