#!/bin/bash
# Tests for hooks/landing-gate.sh — THE LANDING SWEEP (epic-16 wave-03, slice T4c/T4d).
#
# Stop. The gate used to run on SubagentStop and judge the ONE agent that stopped. That
# event is structurally invisible to a skill-frontmatter registration (T4b §3: skill hooks
# live in `appState.sessionHooks` keyed by SESSION id, and every subagent-context event is
# dispatched under the SUBAGENT's id, which has no entry there), so the wall was inert the
# moment registration moved into SKILL.md. It now runs on `Stop`, which IS delivered to the
# skill channel, fires once per orchestrator turn, and — the fact that makes the latency a
# non-issue — is GENERATED BY a background agent's landing, which wakes a fresh turn that
# closes 2.5–3.7 s later (T4b §2.3, §4).
#
# The shape that replaces "judge the stopping agent" is a SWEEP: every roster row whose
# `agent_id` is absent from the payload's `background_tasks[]` has landed, and each one is
# verdicted exactly once, ever.
#
# Governing evidence: .bionic/docs/record/session-20260814-wave-detector-terminal-state/
# t4b-probe-report.md §6 (the ratified mechanism), §2–§4 (its evidence).
#
# HERMETIC. Every payload is crafted and piped straight into the gate; nothing here stops a
# real subagent, touches the live installed hooks, or depends on a live wave. Repos are
# throwaway `git init`s under a mktemp'd sandbox, and the roster/plan fixtures are written
# as files.
#
# THE SWEEPER IS REAL IN EVERY CASE THAT HAS ONE. The gate consumes
# `session-sweeper.sh verdict <name>` and never re-implements its predicate, so a stubbed
# verdict would leave exactly the seam this slice exists to close (rule: seam-blindness —
# a seam substituting the value-under-test leaves the production path unverified). The gate
# resolves the sweeper as its own SIBLING, which is what bootstrap's `hooks/*.sh` install
# produces, so Section 6 gets its absent/erroring sweeper by running a COPY of the gate out
# of a directory holding a different sibling — no env override, no PATH seam.
#
# Usage: bash hooks/landing-gate.test.sh

set -uo pipefail

HOOKS_DIR="$(cd "$(dirname "$0")" && pwd)"
GATE="$HOOKS_DIR/landing-gate.sh"

SANDBOX="$(cd "$(mktemp -d "${TMPDIR:-/tmp}/landing-gate-test.XXXXXX")" && pwd)"
BG_PIDS=""
cleanup() {
  local p
  for p in $BG_PIDS; do kill -9 "$p" 2>/dev/null; done
  chmod -R u+rwX "$SANDBOX" 2>/dev/null
  rm -rf "$SANDBOX"
}
trap cleanup EXIT

PASS=0
FAIL=0
TOTAL=0

ok() { TOTAL=$((TOTAL + 1)); PASS=$((PASS + 1)); echo "PASS: $1"; }
no() { TOTAL=$((TOTAL + 1)); FAIL=$((FAIL + 1)); echo "FAIL: $1"; [ -n "${2:-}" ] && echo "      $2"; return 0; }

expect_status()   { if [ "$2" = "$3" ]; then ok "$1"; else no "$1" "expected exit $2, got $3"; fi; }
expect_contains() { if printf '%s' "$3" | grep -qF -- "$2"; then ok "$1"; else no "$1" "missing [$2] in: $(printf '%s' "$3" | head -3)"; fi; }
expect_absent()   { if printf '%s' "$3" | grep -qF -- "$2"; then no "$1" "unexpectedly present: $2"; else ok "$1"; fi; }
expect_empty()    { if [ -z "$2" ]; then ok "$1"; else no "$1" "expected no output, got: $2"; fi; }
expect_eq()       { if [ "$2" = "$3" ]; then ok "$1"; else no "$1" "expected [$2] got [$3]"; fi; }
section()         { printf '\n=== %s ===\n' "$1"; }

# ---------- fixtures ----------
#
# FIXTURE FIDELITY (declared per rule fixtures-can-pin-away-the-test).
#
#   * Stop payload ENVELOPE — VERBATIM key set from t4b-probe-report.md §2.1, a live Stop
#     captured 2026-08-15 (CLI 2.1.233): background_tasks, cwd, effort, hook_event_name,
#     last_assistant_message, permission_mode, prompt_id, session_crons, session_id,
#     stop_hook_active, transcript_path. The `background_tasks[]` row shape is §2.2's
#     verbatim: {id, type, status, description, agent_type}.
#   * agent ids — the transcript form the platform mints for an Agent dispatch
#     (`a8e3d9b517abc6bf7`, §4), which is the SAME string `tool_response.agentId` returns and
#     the SAME string `background_tasks[].id` carries. That triple identity is the join this
#     slice is built on, so the fixtures spell one form and never three.
#   * roster rows — the roster-state/v1 field set and ORDER written by
#     hooks/dispatch-preflight.sh (the `ROW=` assignment), copied from
#     hooks/session-sweeper.test.sh's `mkrow`. This suite's subject reads the roster for the
#     JOIN KEY only; the contract is read by the sweeper, which is the real one here.
#   * SYNTHESIZED and declared: session ids, plan text, deliverable paths, the marker process
#     a STILL-LIVE row claims. None is a platform surface.

SID="3b51bef0-d7bd-447a-bc65-8916c4b25353"
SID_B="7c2d1a04-55e8-4f31-9a70-1b8c3d0e6f22"

AID_A="a8e3d9b517abc6bf7"
AID_B="ab9751b8c5191a4e5"

# The live half of a Stop payload: one `background_tasks` row per id still running.
bg_tasks() {  # <agent-id>...
  local first=1 id
  printf '['
  for id in "$@"; do
    [ -n "$id" ] || continue
    [ "$first" -eq 1 ] || printf ','
    first=0
    printf '{"id":"%s","type":"subagent","status":"running","description":"a live dispatch","agent_type":"general-purpose"}' "$id"
  done
  printf ']'
}

# THE TEAMMATE'S OWN LIVE ROW. A named teammate is entered in `background_tasks[]` under a
# THIRD id namespace — an opaque nine-character token that appears in no other payload the
# session ever sees — and it NEVER LEAVES that array: measured `status:"running"` on the last
# Stop of the session, 2 m 41 s after the teammate had delivered its own SubagentStop
# (t1-probe-report.md §2.1, §2.3, CLI 2.1.233). Landing-by-disappearance is a subagent-only
# signal, so this row is what the SubagentStop arm must be indifferent to.
bg_teammate() {  # <opaque-id>
  printf '{"id":"%s","type":"teammate","status":"running","description":"a named teammate, still addressable..."}' "$1"
}

stop_payload() {  # <cwd> <session_id> <stop_hook_active> [live-agent-id...]
  local cwd="$1" sid="$2" active="$3"; shift 3
  cat <<JSON
{
  "session_id": "$sid",
  "transcript_path": "/tmp/transcripts/$sid.jsonl",
  "cwd": "$cwd",
  "prompt_id": "e30e6fb0-3868-467c-b092-ca03e55b4cd5",
  "permission_mode": "bypassPermissions",
  "effort": { "level": "high" },
  "hook_event_name": "Stop",
  "stop_hook_active": $active,
  "last_assistant_message": "The background probe agent completed and returned PONG.",
  "background_tasks": $(bg_tasks "$@"),
  "session_crons": []
}
JSON
}

# THE LANDING EVENT FOR A TEAMMATE (session-20260815-landing-supervision, T2). The key set is
# t1-probe-report.md §2.1's verbatim SubagentStop capture: agent_id (the TRANSCRIPT form),
# agent_type (which carries the dispatch NAME for a teammate and the subagent TYPE for an
# async dispatch — both readings are right, for different dispatch modes), agent_transcript_path,
# last_assistant_message, stop_hook_active, and the whole `background_tasks[]` array the Stop
# payload carries. This event reaches the gate through the SETTINGS channel behind
# hooks/agent-context-guard.sh; the skill channel never receives it (t1 §3).
substop_payload() {  # <cwd> <session_id> <agent_id> <agent_type> <stop_hook_active> [live-bg-json]
  local cwd="$1" sid="$2" aid="$3" atype="$4" active="$5" bg="${6:-[]}"
  cat <<JSON
{
  "session_id": "$sid",
  "transcript_path": "/tmp/transcripts/$sid.jsonl",
  "agent_transcript_path": "/tmp/transcripts/$sid/subagents/agent-$aid.jsonl",
  "cwd": "$cwd",
  "prompt_id": "e30e6fb0-3868-467c-b092-ca03e55b4cd5",
  "permission_mode": "bypassPermissions",
  "effort": { "level": "high" },
  "agent_id": "$aid",
  "agent_type": "$atype",
  "hook_event_name": "SubagentStop",
  "stop_hook_active": $active,
  "last_assistant_message": "Both steps completed.",
  "background_tasks": $bg,
  "session_crons": []
}
JSON
}

iso_ago() {  # <seconds ago> -> UTC ISO-8601, the launched_at shape
  date -u -v-"$1"S +%Y-%m-%dT%H:%M:%SZ 2>/dev/null \
    || date -u -d "-$1 seconds" +%Y-%m-%dT%H:%M:%SZ
}

# roster-state/v1, field set and order per hooks/dispatch-preflight.sh's writer.
mkrow() {  # <key=value>...
  local status=confirmed session="$SID" name=agent agent_id="$AID_A" launched_at=""
  local subagent_type=implementor model=opus deliverable="" duration="" progress=""
  local claims="" cadence="" waiver="" tool_use_id=toolu_x source=declared teammate_id="" kv
  for kv in "$@"; do
    case "$kv" in
      source=*)      source="${kv#*=}" ;;
      teammate_id=*) teammate_id="${kv#*=}" ;;
      status=*)      status="${kv#*=}" ;;
      session=*)     session="${kv#*=}" ;;
      name=*)        name="${kv#*=}" ;;
      agent_id=*)    agent_id="${kv#*=}" ;;
      launched_at=*) launched_at="${kv#*=}" ;;
      deliverable=*) deliverable="${kv#*=}" ;;
      duration=*)    duration="${kv#*=}" ;;
      progress=*)    progress="${kv#*=}" ;;
      claims=*)      claims="${kv#*=}" ;;
      cadence=*)     cadence="${kv#*=}" ;;
      waiver=*)      waiver="${kv#*=}" ;;
      tool_use_id=*) tool_use_id="${kv#*=}" ;;
      *) printf 'mkrow: unknown key %s\n' "$kv" >&2; return 1 ;;
    esac
  done
  [ -n "$launched_at" ] || launched_at="$(iso_ago 60)"
  # `teammate_id` is APPENDED rather than slotted, because that is how the writer emits it:
  # hooks/execution-recorder.sh's completion arm substitutes the field when the launch row
  # already carries one and appends it at the end when it does not — and the launch wall
  # never writes it, so every real teammate row carries it last. It is the field that says
  # which namespace the row's id is in, and (this slice) which half of the machinery owns
  # the row's landing verdict.
  printf 'roster-state/v1|status=%s|session=%s|name=%s|agent_id=%s|launched_at=%s|subagent_type=%s|model=%s|deliverable=%s|source=%s|duration=%s|progress=%s|claims=%s|cadence=%s|absent=|waiver=%s|tool_use_id=%s' \
    "$status" "$session" "$name" "$agent_id" "$launched_at" "$subagent_type" "$model" \
    "$deliverable" "$source" "$duration" "$progress" "$claims" "$cadence" "$waiver" "$tool_use_id"
  [ -n "$teammate_id" ] && printf '|teammate_id=%s' "$teammate_id"
  printf '\n'
}

roster_of() { printf '%s/.bionic/tmp/roster-%s.state' "$1" "${2:-$SID}"; }

new_roster() {  # <repo> [sid]
  printf '# bionic session roster — schema roster-state/v1 — machine-local, safe to delete\n' \
    > "$(roster_of "$1" "${2:-$SID}")"
}

add_row() {  # <repo> <key=value>...
  local repo="$1"; shift
  mkrow "$@" >> "$(roster_of "$repo" "$SID")"
}

# The idempotency marker the sweep appends. It rides IN the roster file under its own schema
# prefix, which every roster reader in the fleet filters on (`roster-state/v1|`), so a swept
# line is inert to all of them and cannot outlive the roster it belongs to.
swept_lines() {  # <repo> -> the marker lines, one per verdicted row
  /usr/bin/grep '^landing-swept/v1|' "$(roster_of "$1")" 2>/dev/null
}
swept_count() {  # <repo>
  swept_lines "$1" | /usr/bin/grep -c '|' | tr -d ' '
}

# An ACTIVE wave: the fence-aware `## SDLC State` / `current:` marker the evidence gate,
# stop-guard and dispatch-preflight all read.
plan_active() {  # <repo>
  local d="$1/.bionic/docs/plans/epic-16-landing-contract"
  mkdir -p "$d"
  cat > "$d/wave-01-landing-contract.plan.md" <<'PLAN'
---
governing-skill: superpowers:writing-plans
sdlc-step: 4
canonical_sdlc_version: 13
---

# Wave 01 — landing contract

## SDLC State

integration-branch: main
current: 4
PLAN
}

# A plan whose ONLY `## SDLC State` section is inside a fence: documentation, invisible to
# the parser, so no wave is active. The trap this shape encodes is on the record in
# .claude/rules/hook-authoring.md.
plan_fenced_only() {  # <repo>
  local d="$1/.bionic/docs/plans/epic-16-landing-contract"
  mkdir -p "$d"
  cat > "$d/wave-01-landing-contract.plan.md" <<'PLAN'
---
governing-skill: superpowers:writing-plans
---

# How a plan documents its own format

```
## SDLC State

current: 4
```
PLAN
}

make_repo() {  # <label> -> repo path
  local r="$SANDBOX/$1"
  mkdir -p "$r/.bionic/tmp"
  ( cd "$r" && git init -q . 2>/dev/null )
  printf '%s' "$r"
}

# The standard fixture: an active wave, a roster, and nothing delivered.
make_wave_repo() {  # <label> -> repo path
  local r
  r="$(make_repo "$1")"
  plan_active "$r"
  new_roster "$r"
  printf '%s' "$r"
}

deliver() {  # <repo> <relative path> — a real artifact, written now (after launched_at)
  local p="$1/$2"
  mkdir -p "$(dirname "$p")"
  printf 'the report\n' > "$p"
}

# ---------- running the gate ----------
#
# Sets OUT_STDOUT / OUT_STDERR / RC. Bounded: a gate that hangs inside a Stop hook is a
# defect, and a suite that hangs on it would wedge `bash tests/run.sh`.
run_gate() {  # <gate path> <payload json>
  local gate="$1" json="$2"
  printf '%s' "$json" > "$SANDBOX/payload.json"
  ( exec bash "$gate" < "$SANDBOX/payload.json" ) \
    > "$SANDBOX/gate.out" 2> "$SANDBOX/gate.err" &
  local pid=$!
  BG_PIDS="$BG_PIDS $pid"
  local waited=0
  while kill -0 "$pid" 2>/dev/null && [ "$waited" -lt 200 ]; do
    sleep 0.1; waited=$((waited + 1))
  done
  if kill -0 "$pid" 2>/dev/null; then
    kill -9 "$pid" 2>/dev/null
    RC=124
  else
    wait "$pid"; RC=$?
  fi
  OUT_STDOUT="$(cat "$SANDBOX/gate.out")"
  OUT_STDERR="$(cat "$SANDBOX/gate.err")"
}

REFUSAL_TAIL="Land the contract (write the named artifacts), or stop again to pass — this gate blocks once."

# ================================================================= Section 1
section "Section 1: a LANDED row with an unmet contract refuses the turn's end"

R1="$(make_wave_repo r1)"
add_row "$R1" name=w1-s5 agent_id="$AID_A" deliverable=.bionic/docs/record/never.md \
  launched_at="$(iso_ago 600)"

# No live task carries this agent's id, so it has landed — which is the whole of the
# landed/live discrimination (T4b §2.2: background_tasks answers "who is still running",
# never "who ran and finished").
run_gate "$GATE" "$(stop_payload "$R1" "$SID" false)"
expect_status "1a: a landed UNMET contract refuses the stop (exit 2)" "2" "$RC"
expect_contains "1a: the refusal opens with the contract verdict" \
  "LANDING CONTRACT UNMET" "$OUT_STDERR"
expect_contains "1a: …names the ROW, because a sweep judges rows and not the caller" \
  "w1-s5" "$OUT_STDERR"
expect_contains "1a: …names the artifact that is not on disk" \
  "missing=.bionic/docs/record/never.md" "$OUT_STDERR"
expect_contains "1a: …and tells the reader how to pass" "$REFUSAL_TAIL" "$OUT_STDERR"
expect_empty "1a: the refusal goes to stderr, never stdout" "$OUT_STDOUT"

# IDEMPOTENT. Stop fires once per orchestrator TURN and a landed row stays landed forever,
# so a gate that re-verdicted would refuse every turn end for the rest of the session over
# one agent's failure — the false-alarm shape this machinery exists to end.
run_gate "$GATE" "$(stop_payload "$R1" "$SID" false)"
expect_status "1b: the SAME row is not verdicted twice — the second Stop passes" "0" "$RC"
expect_empty "1b: …silently on stdout" "$OUT_STDOUT"
expect_empty "1b: …and on stderr" "$OUT_STDERR"
expect_eq "1b: …and exactly one marker was written, not two" "1" "$(swept_count "$R1")"
expect_contains "1b: …naming the agent id it closed" "agent_id=$AID_A" "$(swept_lines "$R1")"
expect_contains "1b: …and the state it recorded" "state=UNMET" "$(swept_lines "$R1")"

# BLOCKS ONCE on re-entry too: Claude Code re-enters the stop with stop_hook_active true
# after a hook blocked it, and a gate that refused again would wedge the turn.
R1B="$(make_wave_repo r1b)"
add_row "$R1B" name=w1-s5 agent_id="$AID_A" deliverable=.bionic/docs/record/never.md \
  launched_at="$(iso_ago 600)"
run_gate "$GATE" "$(stop_payload "$R1B" "$SID" true)"
expect_status "1c: stop_hook_active true passes the same unmet contract" "0" "$RC"
expect_empty "1c: …silently" "$OUT_STDERR"
expect_eq "1c: …and takes no verdict at all, so the row is still owed one" \
  "0" "$(swept_count "$R1B")"

# ================================================================= Section 2
section "Section 2: a landed row that DID deliver is closed, silently"

R2="$(make_wave_repo r2)"
add_row "$R2" name=met-row agent_id="$AID_A" deliverable=.bionic/docs/record/landed.md \
  launched_at="$(iso_ago 600)"
deliver "$R2" .bionic/docs/record/landed.md

run_gate "$GATE" "$(stop_payload "$R2" "$SID" false)"
expect_status "2a: a landed MET contract passes" "0" "$RC"
expect_empty "2a: …silently — a met contract is not news" "$OUT_STDERR"
expect_eq "2a: …and is marked swept, so it is never re-read" "1" "$(swept_count "$R2")"
expect_contains "2a: …recording the state the verb computed" "state=MET" "$(swept_lines "$R2")"

# ================================================================= Section 3
section "Section 3: STILL-LIVE by the payload — a running agent is skipped, not judged"

R3="$(make_wave_repo r3)"
add_row "$R3" name=live-row agent_id="$AID_A" deliverable=.bionic/docs/record/never.md \
  launched_at="$(iso_ago 600)"

# The agent is IN background_tasks: it has not landed, so there is nothing to hold it to yet.
run_gate "$GATE" "$(stop_payload "$R3" "$SID" false "$AID_A")"
expect_status "3a: a row still in background_tasks passes" "0" "$RC"
expect_empty "3a: …silently" "$OUT_STDERR"
expect_eq "3a: …and is NOT marked swept — its verdict is still owed" "0" "$(swept_count "$R3")"

# …and when it lands, the same roster is judged for the first time.
run_gate "$GATE" "$(stop_payload "$R3" "$SID" false)"
expect_status "3b: once it drops out of background_tasks it is judged, and refuses" "2" "$RC"
expect_contains "3b: …naming its artifact" "missing=.bionic/docs/record/never.md" "$OUT_STDERR"
expect_eq "3b: …and is marked swept exactly once" "1" "$(swept_count "$R3")"

# A live sibling does not shield a landed row, and a landed sibling does not implicate a
# live one: the discrimination is per row, by id.
R3C="$(make_wave_repo r3c)"
add_row "$R3C" name=landed-one agent_id="$AID_A" deliverable=.bionic/docs/record/never.md \
  launched_at="$(iso_ago 600)" tool_use_id=toolu_ONE
add_row "$R3C" name=flying-one agent_id="$AID_B" deliverable=.bionic/docs/record/never2.md \
  launched_at="$(iso_ago 600)" tool_use_id=toolu_TWO
run_gate "$GATE" "$(stop_payload "$R3C" "$SID" false "$AID_B")"
expect_status "3c: one landed and one live — the landed one refuses" "2" "$RC"
expect_contains "3c: …naming the landed row" "landed-one" "$OUT_STDERR"
expect_absent "3c: …and never the row still in flight" "flying-one" "$OUT_STDERR"
expect_eq "3c: …with one marker, for the landed row alone" "1" "$(swept_count "$R3C")"

# ================================================================= Section 4
section "Section 4: relevance and ambiguity — every way out is silent"

R4="$(make_wave_repo r4)"
add_row "$R4" name=w1-s5 agent_id="$AID_A" deliverable=.bionic/docs/record/never.md \
  launched_at="$(iso_ago 600)"

# A SubagentStop whose id belongs to a SUBAGENT row is not this arm's business either: the
# roster's responsibility partition gives async dispatches to the Stop-sweep, which judges
# them by disappearance from `background_tasks[]`, and teammates to the SubagentStop arm.
# Verdicting here would not merely duplicate the sweep — it would STEAL the refusal, since
# the marker this arm writes is what tells the sweep a row is answered for, and the sweep's
# refusal is the one that reaches the orchestrator (Section 12's rationale).
run_gate "$GATE" "$(substop_payload "$R4" "$SID" "$AID_A" general-purpose false)"
expect_status "4a: a SubagentStop over a SUBAGENT row belongs to the sweep — pass" "0" "$RC"
expect_empty "4a: …silently" "$OUT_STDERR"
expect_eq "4a: …and nothing is swept out from under the sweep" "0" "$(swept_count "$R4")"

run_gate "$GATE" "$(stop_payload "" "$SID" false)"
expect_status "4b: no cwd — the repo is unresolvable, pass" "0" "$RC"

run_gate "$GATE" "$(stop_payload "$SANDBOX/not-a-repo" "$SID" false)"
expect_status "4c: a cwd outside any repo passes" "0" "$RC"

run_gate "$GATE" "$(stop_payload "$R4" "" false)"
expect_status "4d: no session key — no roster to scope to, pass" "0" "$RC"

run_gate "$GATE" "$(stop_payload "$R4" "$SID_B" false)"
expect_status "4e: another session's Stop reads that session's (absent) roster, pass" "0" "$RC"

run_gate "$GATE" "not json at all"
expect_status "4f: an unparseable payload passes" "0" "$RC"

R4B="$(make_repo r4b)"
plan_active "$R4B"
run_gate "$GATE" "$(stop_payload "$R4B" "$SID" false)"
expect_status "4g: no roster file at all passes" "0" "$RC"

# THE UNJOINABLE ROW. `agent_id=` is empty until hooks/execution-recorder.sh's roster arm
# completes the launch row, and a row that never got one cannot be placed on either side of
# the landed/live line. Judging it would hold an agent to a contract on the strength of a
# field we do not have; the ambiguity direction is the same as every other one here.
R4C="$(make_wave_repo r4c)"
add_row "$R4C" name=never-spawned agent_id= status=intended \
  deliverable=.bionic/docs/record/never.md launched_at="$(iso_ago 600)"
run_gate "$GATE" "$(stop_payload "$R4C" "$SID" false)"
expect_status "4h: a row with no agent_id cannot be placed — pass" "0" "$RC"
expect_empty "4h: …silently, claiming nothing about a dispatch that may never have spawned" \
  "$OUT_STDERR"
expect_eq "4h: …and is not marked swept, so a later identification still gets its verdict" \
  "0" "$(swept_count "$R4C")"

# ================================================================= Section 5
section "Section 5: no active wave — nothing to hold anyone to"

R5="$(make_repo r5)"
new_roster "$R5"
add_row "$R5" name=w1-s5 agent_id="$AID_A" deliverable=.bionic/docs/record/never.md \
  launched_at="$(iso_ago 600)"
run_gate "$GATE" "$(stop_payload "$R5" "$SID" false)"
expect_status "5a: no plan at all — the same unmet roster passes" "0" "$RC"
expect_eq "5a: …and nothing is swept outside a wave" "0" "$(swept_count "$R5")"

R5B="$(make_repo r5b)"
plan_fenced_only "$R5B"
new_roster "$R5B"
add_row "$R5B" name=w1-s5 agent_id="$AID_A" deliverable=.bionic/docs/record/never.md \
  launched_at="$(iso_ago 600)"
run_gate "$GATE" "$(stop_payload "$R5B" "$SID" false)"
expect_status "5b: a fenced-only SDLC State is documentation, not a live wave — pass" "0" "$RC"

# ================================================================= Section 6
section "Section 6: fail-open — every way the verdict can fail to answer"

# The gate resolves the sweeper as its own sibling. The cases below run a COPY of the gate
# from a directory whose sibling differs, which is the production resolution path under a
# different filesystem, not a substituted seam.
R6="$(make_wave_repo r6)"
add_row "$R6" name=w1-s5 agent_id="$AID_A" deliverable=.bionic/docs/record/never.md \
  launched_at="$(iso_ago 600)"

NOSWEEP="$SANDBOX/hooks-nosweeper"
mkdir -p "$NOSWEEP"
cp "$GATE" "$NOSWEEP/landing-gate.sh" 2>/dev/null
run_gate "$NOSWEEP/landing-gate.sh" "$(stop_payload "$R6" "$SID" false)"
expect_status "6a: the sweeper script is absent — pass, do not block on a verdict we cannot take" "0" "$RC"
expect_empty "6a: …silently" "$OUT_STDERR"
expect_eq "6a: …and mark nothing swept on an answer we never got" "0" "$(swept_count "$R6")"

BADSWEEP="$SANDBOX/hooks-badsweeper"
mkdir -p "$BADSWEEP"
cp "$GATE" "$BADSWEEP/landing-gate.sh" 2>/dev/null
printf '#!/bin/bash\nexit 7\n' > "$BADSWEEP/session-sweeper.sh"
chmod +x "$BADSWEEP/session-sweeper.sh"
run_gate "$BADSWEEP/landing-gate.sh" "$(stop_payload "$R6" "$SID" false)"
expect_status "6b: the sweeper errors — pass" "0" "$RC"
expect_eq "6b: …and the row stays owed a verdict" "0" "$(swept_count "$R6")"

QUIETSWEEP="$SANDBOX/hooks-quietsweeper"
mkdir -p "$QUIETSWEEP"
cp "$GATE" "$QUIETSWEEP/landing-gate.sh" 2>/dev/null
printf '#!/bin/bash\nexit 1\n' > "$QUIETSWEEP/session-sweeper.sh"
chmod +x "$QUIETSWEEP/session-sweeper.sh"
run_gate "$QUIETSWEEP/landing-gate.sh" "$(stop_payload "$R6" "$SID" false)"
expect_status "6c: exit 1 with no verdict line for this row — pass" "0" "$RC"
expect_eq "6c: …and nothing is marked closed on a line that was never printed" \
  "0" "$(swept_count "$R6")"

# A symlinked roster makes the verdict verb REFUSE (exit 2). That is the gate's fail-open
# path, and it is the one direction a hostile repo could otherwise use to aim this gate: it
# must never turn a refusal into a block. The gate refuses to WRITE through the link too.
R6B="$(make_repo r6b)"
plan_active "$R6B"
REAL_ROSTER="$SANDBOX/elsewhere-roster.state"
printf '# bionic session roster — schema roster-state/v1 — machine-local, safe to delete\n' > "$REAL_ROSTER"
mkrow name=w1-s5 agent_id="$AID_A" deliverable=.bionic/docs/record/never.md \
  launched_at="$(iso_ago 600)" >> "$REAL_ROSTER"
ln -s "$REAL_ROSTER" "$(roster_of "$R6B")"
run_gate "$GATE" "$(stop_payload "$R6B" "$SID" false)"
expect_status "6d: a symlinked roster — the gate passes, never blocks" "0" "$RC"
expect_absent "6d: …and says nothing about a contract it never read" "LANDING CONTRACT" "$OUT_STDERR"
expect_absent "6d: …and writes no marker through the link" "landing-swept" "$(cat "$REAL_ROSTER")"

# ================================================================= Section 7
section "Section 7: the join is by agent id — an UNNAMED dispatch is judged like any other"

# `name` is optional at dispatch, so the roster's `name=` can be empty; the sweeper folds
# such a row under `(unnamed)`. The join that decides landed-vs-live is the AGENT ID, which
# every dispatch has, so an unnamed one is held to its contract exactly like a named one.
# This is the §5.1 defect closed: nothing on this path reads `agent_type`.
R7="$(make_wave_repo r7)"
add_row "$R7" name= agent_id="$AID_A" deliverable=.bionic/docs/record/never.md \
  launched_at="$(iso_ago 600)"
run_gate "$GATE" "$(stop_payload "$R7" "$SID" false)"
expect_status "7a: an unnamed dispatch still refuses on its own contract" "2" "$RC"
expect_contains "7a: …under the name the verb folds it to" "(unnamed)" "$OUT_STDERR"
expect_contains "7a: …naming its artifact" "missing=.bionic/docs/record/never.md" "$OUT_STDERR"
expect_contains "7a: …and the marker keys on the id, which is what it actually has" \
  "agent_id=$AID_A" "$(swept_lines "$R7")"

# The same row, still in flight, is skipped by the same join.
R7B="$(make_wave_repo r7b)"
add_row "$R7B" name= agent_id="$AID_A" deliverable=.bionic/docs/record/never.md \
  launched_at="$(iso_ago 600)"
run_gate "$GATE" "$(stop_payload "$R7B" "$SID" false "$AID_A")"
expect_status "7b: …and is skipped while its id is still in background_tasks" "0" "$RC"

# ================================================================= Section 8
section "Section 8: the states the sweep must never refuse"

R8="$(make_wave_repo r8)"
# FIXTURE FIDELITY (wave-01 Step-6 review S-1): a genuine waiver row names NO artifact — the
# wall's waiver label reads "why this dispatch produces nothing durable".
add_row "$R8" name=waived-row agent_id="$AID_A" waiver="exploratory probe" \
  launched_at="$(iso_ago 600)" tool_use_id=toolu_WAIVED
run_gate "$GATE" "$(stop_payload "$R8" "$SID" false)"
expect_status "8a: a waived row (no artifact declared) passes" "0" "$RC"
expect_empty "8a: …silently" "$OUT_STDERR"

# STILL-LIVE by the ROW's own claim: the verdict verb owns that judgment, and the gate
# honours it rather than reading "not delivered" as a failure.
R8B="$(make_wave_repo r8b)"
MARKER="$SANDBOX/bionic-landing-gate-marker-91744.sh"
printf '#!/bin/bash\nsleep 60\n' > "$MARKER"
chmod +x "$MARKER"
"$MARKER" & MARKER_PID=$!
BG_PIDS="$BG_PIDS $MARKER_PID"
add_row "$R8B" name=claimed-row agent_id="$AID_A" deliverable=.bionic/docs/record/never.md \
  claims="$MARKER" launched_at="$(iso_ago 600)"
run_gate "$GATE" "$(stop_payload "$R8B" "$SID" false)"
expect_status "8b: a STILL-LIVE row passes" "0" "$RC"
expect_empty "8b: …silently" "$OUT_STDERR"
kill -9 "$MARKER_PID" 2>/dev/null

# AMBIGUOUS: two contracts share one name, so no reader can tell whose artifact is whose.
R8C="$(make_wave_repo r8c)"
deliver "$R8C" .bionic/docs/record/first.md
add_row "$R8C" name=dup agent_id="$AID_A" deliverable=.bionic/docs/record/first.md \
  tool_use_id=toolu_01FIRST launched_at="$(iso_ago 900)"
add_row "$R8C" name=dup agent_id="$AID_A" deliverable=.bionic/docs/record/second.md \
  tool_use_id=toolu_01SECOND launched_at="$(iso_ago 600)"
run_gate "$GATE" "$(stop_payload "$R8C" "$SID" false)"
expect_status "8c: an ambiguous name refuses nobody" "0" "$RC"
expect_empty "8c: …silently, naming no artifact that may not be its job" "$OUT_STDERR"

# ================================================================= Section 9
section "Section 9: an ACKED row is closed for every reader (epic-16 w2 S3, R2)"

SWEEPER_BIN="$(cd "$(dirname "$GATE")" && pwd)/session-sweeper.sh"
ack_row() {  # <repo> <name>
  ( cd "$1" && CLAUDE_CODE_SESSION_ID="$SID" bash "$SWEEPER_BIN" ack "$2" ) >/dev/null 2>&1
  return 0
}

R9="$(make_wave_repo r9)"
add_row "$R9" name=w2-s3 agent_id="$AID_A" deliverable=.bionic/docs/record/never.md \
  launched_at="$(iso_ago 600)"
run_gate "$GATE" "$(stop_payload "$R9" "$SID" false)"
expect_status "9a: precondition — an unacked UNMET contract refuses" "2" "$RC"

R9B="$(make_wave_repo r9b)"
add_row "$R9B" name=w2-s3 agent_id="$AID_A" deliverable=.bionic/docs/record/never.md \
  launched_at="$(iso_ago 600)"
ack_row "$R9B" w2-s3
run_gate "$GATE" "$(stop_payload "$R9B" "$SID" false)"
expect_status "9b: once acked, the same sweep passes" "0" "$RC"
expect_empty "9c: …silently — the orchestrator already accounted for it" "$OUT_STDERR"
expect_eq "9d: …and the row is still marked swept, so it is asked about once" \
  "1" "$(swept_count "$R9B")"

# ================================================================= Section 10
section "Section 10: the sweep records only its own marker, and only in the roster"

R10="$(make_wave_repo r10)"
add_row "$R10" name=mine agent_id="$AID_A" deliverable=.bionic/docs/record/mine.md \
  launched_at="$(iso_ago 600)" tool_use_id=toolu_MINE
deliver "$R10" .bionic/docs/record/mine.md
BEFORE="$(ls -A "$R10/.bionic/tmp" | sort)"
run_gate "$GATE" "$(stop_payload "$R10" "$SID" false)"
AFTER="$(ls -A "$R10/.bionic/tmp" | sort)"
expect_eq "10a: the sweep creates no state file of its own" "$BEFORE" "$AFTER"
expect_eq "10b: the roster keeps exactly the row it was given — no roster row appended" \
  "1" "$(/usr/bin/grep -c '^roster-state/v1|' "$(roster_of "$R10")" | tr -d ' ')"
expect_eq "10c: …and exactly one marker line beside it" "1" "$(swept_count "$R10")"

# THE MARKER IS INERT TO THE ROSTER'S OWN READER. The sweeper folds `roster-state/v1|` rows
# and nothing else, so the verdict it computes after a sweep is the verdict it computed
# before one — a marker that changed an answer would be this gate quietly acquiring the
# authority ADR-003 denies it.
R10_VERDICT=$( cd "$R10" && CLAUDE_CODE_SESSION_ID="$SID" bash "$SWEEPER_BIN" verdict mine 2>/dev/null \
               | /usr/bin/grep -F 'landing-verdict/v1|' | head -1 | tr '|' '\n' \
               | /usr/bin/grep '^state=' | cut -d= -f2- )
expect_eq "10d: the verb reads the swept roster exactly as it read the unswept one" \
  "MET" "$R10_VERDICT"

# ================================================================= Section 11
section "Section 11: the payload session key is shape-checked before it becomes a path"

# `roster-${SID}.state` interpolates the payload's session id straight into a path the sweep
# now WRITES to, and the symlink guards check the state directory and the exact filenames —
# so a key carrying path separators leaves the guarded directory entirely rather than
# tripping a guard.
R11="$(make_wave_repo r11)"
mkdir -p "$R11/.bionic/tmp/roster-x" "$R11/planted"
SID_TRAVERSAL='x/../../../planted/evil'
PLANTED="$R11/planted/evil.state"
printf '# bionic session roster — schema roster-state/v1 — machine-local, safe to delete\n' > "$PLANTED"
mkrow name=w1-s5 session="$SID_TRAVERSAL" agent_id="$AID_A" \
  deliverable=.bionic/docs/record/never.md launched_at="$(iso_ago 600)" >> "$PLANTED"
expect_eq "11a: the traversal fixture really does escape the state directory (not vacuous)" \
  "yes" "$([ -e "$R11/.bionic/tmp/roster-${SID_TRAVERSAL}.state" ] && echo yes || echo no)"
run_gate "$GATE" "$(stop_payload "$R11" "$SID_TRAVERSAL" false)"
expect_status "11b: a session key carrying path separators is not a session key — pass" "0" "$RC"
expect_absent "11c: …and no verdict is taken over the roster it reached" \
  "LANDING CONTRACT" "$OUT_STDERR"
expect_absent "11d: …and no marker is written into it" "landing-swept" "$(cat "$PLANTED")"

# ================================================================= Section 12
section "Section 12: TEAMMATES LAND AT SubagentStop (session-20260815 T2, R1/AC-2)"

# WHY A SECOND ARM AND NOT A BETTER JOIN. The sweep's discrimination is "a roster row whose
# agent_id is absent from background_tasks[] has landed", and for a named teammate that
# predicate is wrong in BOTH directions (t1-probe-report.md §2.3): the three id namespaces a
# teammate carries never join — the addressing form at dispatch, the transcript form on
# SubagentStart/Stop, and an opaque token in background_tasks[] — and the teammate's row never
# leaves that array at all, so a filled agent_id would read as LANDED on the first Stop after
# dispatch, 2.8 s in, while the teammate is still working. SubagentStop is the transition
# itself, delivered with every fact the verdict needs in one payload: no join to reconstruct,
# no disappearance to infer.
#
# The arm reuses the sweep's own machinery unchanged — the same `session-sweeper.sh verdict`
# verb, the same landing-swept/v1 marker through the same append, the same refusal text — so
# what is new here is WHICH ROW is judged and WHEN, and nothing about how.
TEAM_AID="aw2mate-fdaa80c4b3cb703f"        # transcript form: `a` + name + `-` + 16 hex (t1 §2.2)
TEAM_ADDR="w2mate@session-3b51bef0"        # addressing form, the field that says "teammate"
TEAM_BG="[$(bg_teammate t5triyxvo)]"       # its own still-running row, for the whole session

R12="$(make_wave_repo r12)"
add_row "$R12" name=w2mate agent_id="$TEAM_AID" teammate_id="$TEAM_ADDR" \
  deliverable=.bionic/docs/record/mate.md launched_at="$(iso_ago 600)"
deliver "$R12" .bionic/docs/record/mate.md
run_gate "$GATE" "$(substop_payload "$R12" "$SID" "$TEAM_AID" w2mate false "$TEAM_BG")"
expect_status "12a: a teammate that delivered lands MET, and passes" "0" "$RC"
expect_empty "12a: …silently — a met contract is not news" "$OUT_STDERR"
expect_eq "12a: …and is marked swept, through the same append the sweep uses" \
  "1" "$(swept_count "$R12")"
expect_contains "12a: …recording the state the verb computed" "state=MET" "$(swept_lines "$R12")"
expect_contains "12a: …keyed by the transcript-form id ARM 3 filled in" \
  "agent_id=$TEAM_AID" "$(swept_lines "$R12")"

R12B="$(make_wave_repo r12b)"
add_row "$R12B" name=w2mate agent_id="$TEAM_AID" teammate_id="$TEAM_ADDR" \
  deliverable=.bionic/docs/record/never.md launched_at="$(iso_ago 600)"
run_gate "$GATE" "$(substop_payload "$R12B" "$SID" "$TEAM_AID" w2mate false "$TEAM_BG")"
expect_status "12b: a teammate that did NOT deliver is refused (exit 2)" "2" "$RC"
expect_contains "12b: …in the sweep's own words, unedited" "LANDING CONTRACT UNMET" "$OUT_STDERR"
expect_contains "12b: …naming the row" "w2mate" "$OUT_STDERR"
expect_contains "12b: …and the artifact that is not on disk" \
  "missing=.bionic/docs/record/never.md" "$OUT_STDERR"
expect_contains "12b: …and telling the reader how to pass" "$REFUSAL_TAIL" "$OUT_STDERR"
expect_empty "12b: the refusal goes to stderr, never stdout" "$OUT_STDOUT"
expect_contains "12b: …and the row is marked, so it is asked about once" \
  "state=UNMET" "$(swept_lines "$R12B")"

# ONCE PER ROW, EVER — the same promise the sweep makes. A blocked SubagentStop is re-entered
# with stop_hook_active true (the harness's own guidance for Stop/SubagentStop hooks, read out
# of the shipped binary), and the teammate can stop again after that: neither re-entry may
# re-refuse, or the agent is wedged in a loop it has no way out of.
run_gate "$GATE" "$(substop_payload "$R12B" "$SID" "$TEAM_AID" w2mate true "$TEAM_BG")"
expect_status "12c: the blocked re-entry (stop_hook_active) passes" "0" "$RC"
expect_empty "12c: …silently" "$OUT_STDERR"
expect_eq "12c: …and takes no second verdict" "1" "$(swept_count "$R12B")"
run_gate "$GATE" "$(substop_payload "$R12B" "$SID" "$TEAM_AID" w2mate false "$TEAM_BG")"
expect_status "12d: a later SubagentStop for the same marked row passes" "0" "$RC"
expect_empty "12d: …silently" "$OUT_STDERR"
expect_eq "12d: …and writes no second marker" "1" "$(swept_count "$R12B")"

# THE ROW IS STILL IN background_tasks[] IN EVERY CASE ABOVE — that is the fixture's point,
# not an accident (t1 §2.3). This arm must not consult the live set: the event IS the landing.
expect_contains "12e: the fixtures really do keep the teammate live in background_tasks" \
  '"type":"teammate"' "$TEAM_BG"

# THE NAME FALLBACK. `agent_id=` is filled by the recorder's identification arm at
# SubagentStart; if that event was lost, the row is still joinable here because SubagentStop's
# `agent_type` carries the dispatch NAME for a teammate (t1 §2.1 — the field wave-03 read as
# the subagent type, which it is for an async dispatch and is not for a teammate). The marker
# then keys on the id the PAYLOAD carries, which is the same transcript form the join would
# have written, so the row is still answered for exactly once.
R12F="$(make_wave_repo r12f)"
add_row "$R12F" name=w2mate agent_id= status=confirmed teammate_id="$TEAM_ADDR" \
  deliverable=.bionic/docs/record/never.md launched_at="$(iso_ago 600)"
run_gate "$GATE" "$(substop_payload "$R12F" "$SID" "$TEAM_AID" w2mate false "$TEAM_BG")"
expect_status "12f: an unidentified teammate row is joined by NAME, and refuses" "2" "$RC"
expect_contains "12f: …naming the row" "w2mate" "$OUT_STDERR"
expect_contains "12f: …and the marker keys on the id the payload carried" \
  "agent_id=$TEAM_AID" "$(swept_lines "$R12F")"
run_gate "$GATE" "$(substop_payload "$R12F" "$SID" "$TEAM_AID" w2mate false "$TEAM_BG")"
expect_eq "12f: …once, and not again on the next stop" "1" "$(swept_count "$R12F")"

# THE PHANTOMS. Roughly nine harness-internal SubagentStops arrive per session carrying an
# `agent_type` of "" and an id on no row of ours (t1 §4.6). They are a read to budget for, not
# a correctness problem — but only if a no-match is silent.
R12G="$(make_wave_repo r12g)"
add_row "$R12G" name=w2mate agent_id="$TEAM_AID" teammate_id="$TEAM_ADDR" \
  deliverable=.bionic/docs/record/never.md launched_at="$(iso_ago 600)"
run_gate "$GATE" "$(substop_payload "$R12G" "$SID" "a12b83613c5edc596" "" false "$TEAM_BG")"
expect_status "12g: a phantom SubagentStop matching no roster row passes" "0" "$RC"
expect_empty "12g: …silently" "$OUT_STDERR"
expect_eq "12g: …and marks nothing, so the real row keeps its verdict owed" \
  "0" "$(swept_count "$R12G")"

# The same ways out the sweep has, on the new event.
R12H="$(make_repo r12h)"
new_roster "$R12H"
add_row "$R12H" name=w2mate agent_id="$TEAM_AID" teammate_id="$TEAM_ADDR" \
  deliverable=.bionic/docs/record/never.md launched_at="$(iso_ago 600)"
run_gate "$GATE" "$(substop_payload "$R12H" "$SID" "$TEAM_AID" w2mate false "$TEAM_BG")"
expect_status "12h: no active wave — a teammate is held to nothing" "0" "$RC"
expect_eq "12h: …and nothing is marked outside a wave" "0" "$(swept_count "$R12H")"

R12I="$(make_wave_repo r12i)"
add_row "$R12I" name=w2mate agent_id="$TEAM_AID" teammate_id="$TEAM_ADDR" \
  waiver="exploratory probe" launched_at="$(iso_ago 600)"
run_gate "$GATE" "$(substop_payload "$R12I" "$SID" "$TEAM_AID" w2mate false "$TEAM_BG")"
expect_status "12i: a teammate row declaring no artifact passes" "0" "$RC"
expect_empty "12i: …silently" "$OUT_STDERR"
expect_eq "12i: …and is not marked, exactly as the sweep leaves it" "0" "$(swept_count "$R12I")"

# ================================================================= Section 13
section "Section 13: the sweep SKIPS teammate rows — the partition, both halves"

# THIS SKIP IS LOAD-BEARING, not hygiene. Once the recorder's scoped name join fills a
# teammate row's `agent_id` with the transcript form, that id is absent from
# `background_tasks[]` by construction — the array keys teammates under a different namespace
# entirely — so the sweep's landed/live predicate reads EVERY teammate as landed on the first
# Stop after dispatch, 2.8 s in, and turns today's silence into a false refusal on every
# teammate dispatch (t1 §2.3). The two arms partition the roster on one field: rows carrying a
# `teammate_id=` belong to SubagentStop, rows without it to the sweep.
R13="$(make_wave_repo r13)"
add_row "$R13" name=w2mate agent_id="$TEAM_AID" teammate_id="$TEAM_ADDR" \
  deliverable=.bionic/docs/record/never.md launched_at="$(iso_ago 600)"
run_gate "$GATE" "$(stop_payload "$R13" "$SID" false)"
expect_status "13a: a teammate row with a filled id is NOT swept-landed" "0" "$RC"
expect_empty "13a: …and the sweep says nothing about it" "$OUT_STDERR"
expect_eq "13a: …and marks nothing, leaving the verdict to its own event" \
  "0" "$(swept_count "$R13")"

# THE DISCRIMINATING PAIR: the same row, same id, same missing artifact, differing only in the
# field the partition reads. Without it this section would pass over any implementation that
# simply stopped sweeping.
R13B="$(make_wave_repo r13b)"
add_row "$R13B" name=w2mate agent_id="$TEAM_AID" \
  deliverable=.bionic/docs/record/never.md launched_at="$(iso_ago 600)"
run_gate "$GATE" "$(stop_payload "$R13B" "$SID" false)"
expect_status "13b: …while the identical row WITHOUT teammate_id is swept and refuses" "2" "$RC"
expect_contains "13b: …naming it" "w2mate" "$OUT_STDERR"
expect_eq "13b: …and marked once" "1" "$(swept_count "$R13B")"

# A teammate row does not shield its neighbours: the skip is per row, on the same fold.
R13C="$(make_wave_repo r13c)"
add_row "$R13C" name=w2mate agent_id="$TEAM_AID" teammate_id="$TEAM_ADDR" \
  deliverable=.bionic/docs/record/never.md launched_at="$(iso_ago 600)" tool_use_id=toolu_MATE
add_row "$R13C" name=async-one agent_id="$AID_B" \
  deliverable=.bionic/docs/record/never2.md launched_at="$(iso_ago 600)" tool_use_id=toolu_ASYNC
run_gate "$GATE" "$(stop_payload "$R13C" "$SID" false)"
expect_status "13c: a landed subagent beside a teammate still refuses" "2" "$RC"
expect_contains "13c: …naming the subagent row" "async-one" "$OUT_STDERR"
expect_absent "13c: …and never the teammate, whose event has not arrived" "w2mate" "$OUT_STDERR"
expect_eq "13c: …with one marker, for the subagent alone" "1" "$(swept_count "$R13C")"

# ---------- summary ----------
printf '\n---\n%d/%d passed, %d failed\n' "$PASS" "$TOTAL" "$FAIL"
[ "$FAIL" -eq 0 ]
